export const WORD_BANK: Record<string, string[]> = {
    animals: [
        "TIGER", "ZEBRA", "PANDA", "EAGLE", "SNAKE", "HORSE", "WHALE", "SHARK", "BEARS", "LIONS",
        "FOXES", "WOLVES", "RABBIT", "MONKEY", "GIRAFFE", "LEOPARD", "DOLPHIN", "PENGUIN", "OSTRICH", "CAMEL",
        "CHEETAH", "ELEPHANT", "HAMSTER", "KANGAROO", "SQUIRREL", "GORILLA", "PEACOCK", "PANTHER", "BUFFALO", "MEERKAT",
        "ANTELOPE", "PLATYPUS", "STARFISH", "SEAHORSE", "JELLYFISH", "LOBSTER", "SCORPION", "VULTURE", "PELICAN", "FLAMINGO",
        "HEDGEHOG", "RACCOON", "PARROT", "TURTLE", "LIZARD", "CROCODILE", "ALLIGATOR", "RHINOCEROS", "HIPPOPOTAMUS", "CHIMPANZEE",
        "HYENA", "JACKAL", "LEMUR", "ORANGUTAN", "WALRUS", "SEALION", "MANATEE", "NARWHAL", "STINGRAY", "BARRACUDA",
        "PIRANHA", "GOLDFISH", "CATFISH", "SALMON", "TROUT", "SNAPPER", "GROUPER", "MARLIN", "SWORDFISH", "DOLPHIN",
        "PORPOISE", "OCTOPUS", "SQUID", "CUTTLEFISH", "NAUTILUS", "OYSTER", "MUSSEL", "SCALLOP", "ABALONE", "CLAM",
        "SNAIL", "SLUG", "SPIDER", "BEETLE", "BUTTERFLY", "MOTH", "DRAGONFLY", "MANTIS", "CRICKET", "LOCUST",
        "HORNET", "WASP", "TERMITE", "COCKROACH", "LADYBUG", "FIREFLY", "CENTIPEDE", "MILLIPEDE", "WORM", "LEECH"
    ],
    space: [
        "PLANET", "COMET", "STARS", "LUNAR", "ORBIT", "SOLAR", "VENUS", "MARS", "SATURN", "JUPITER",
        "METEOR", "GALAXY", "NEBULA", "ROCKET", "COSMOS", "PULSAR", "QUASAR", "APOLLO", "ASTEROID", "ECLIPSE",
        "MERCURY", "URANUS", "NEPTUNE", "PLUTO", "SUNSPOT", "AURORA", "ZENITH", "AZIMUTH", "HORIZON", "EQUINOX",
        "SOLSTICE", "ZODIAC", "CONSTELLATION", "CASSIOPEIA", "ANDROMEDA", "ORION", "PEGASUS", "SCORPIUS", "SAGITTARIUS", "AQUARIUS",
        "GEMINI", "TAURUS", "LIBRA", "VIRGO", "LEO", "CANCER", "ARIES", "PISCES", "CAPRICORN", "TELESCOPE",
        "SATELLITE", "SPACESHIP", "SHUTTLE", "LANDER", "ROVER", "PROBE", "CAPSULE", "STATION", "MODULE", "ROCKETRY",
        "THRUSTER", "BOOSTER", "PAYLOAD", "COCKPIT", "AIRLOCK", "GRAVITY", "VACUUM", "PLASMA", "RADIATION", "FUSION",
        "FISSION", "MAGNETISM", "ORBITAL", "TRAJECTORY", "VELOCITY", "LIGHTYEAR", "PARSEC", "UNIVERSE", "MULTIVERSE", "DIMENSION",
        "WORMHOLE", "BLACKHOLE", "SUPERNOVA", "HYPERNOVA", "NIGHTSKY", "STARLIGHT", "MOONBEAM", "SUNLIGHT", "TWILIGHT", "MIDNIGHT",
        "INFINITY", "ETERNITY", "VOID", "ABYSS", "DARKNESS", "SPACEWALK", "LAUNCHPAD", "COUNTDOWN", "BLASTOFF", "REENTRY"
    ],
    fruits: [
        "APPLE", "MANGO", "GRAPE", "LEMON", "PEACH", "MELON", "BERRY", "ORANGE", "BANANA", "CHERRY",
        "PAPAYA", "COCONUT", "PINEAPPLE", "KIWI", "PLUM", "PEAR", "LIME", "GUAVA", "APRICOT", "LYCHEE",
        "AVOCADO", "FIG", "DATE", "RAISIN", "PRUNE", "OLIVE", "TOMATO", "EGGPLANT", "PUMPKIN", "SQUASH",
        "CUCUMBER", "PEPPER", "CHILI", "CORN", "PEA", "BEAN", "NUT", "ALMOND", "WALNUT", "PECAN",
        "CASHEW", "PISTACHIO", "HAZELNUT", "PEANUT", "CHESTNUT", "ACORN", "SEED", "KERNEL", "GRAIN", "WHEAT",
        "RICE", "BARLEY", "OATS", "RYE", "MAIZE", "MILLET", "SORGHUM", "BAMBOO", "SUGARCANE", "COTTON",
        "FLAX", "HEMP", "JUTE", "SISAL", "RAMIE", "KAPOK", "COIR", "STRAW", "HAY", "SILAGE",
        "FODDER", "FORAGE", "PASTURE", "MEADOW", "GRASS", "TURF", "LAWN", "SOD", "PEAT", "MOSS",
        "LICHEN", "FUNGUS", "MUSHROOM", "TOADSTOOL", "TRUFFLE", "YEAST", "MOLD", "MILDEW", "SPORE", "POLLEN",
        "NECTAR", "SAP", "RESIN", "GUM", "LATEX", "WAX", "OIL", "FAT", "PROTEIN", "STARCH"
    ],
    ocean: [
        "CORAL", "WAVES", "PEARL", "SHORE", "TIDE", "REEF", "KELP", "WHALE", "SHARK", "DOLPHIN",
        "OCTOPUS", "JELLYFISH", "STARFISH", "SEAHORSE", "CLAM", "SEAL", "CRAB", "LOBSTER", "URCHIN", "ALGAE",
        "PLANKTON", "KRILL", "SHRIMP", "PRAWN", "CRAYFISH", "BARNACLE", "LIMPET", "WHELK", "CONCH", "NAUTILUS",
        "ANEMONE", "SPONGE", "HYDROZOAN", "BRYOZOAN", "TUNICATE", "LANCELET", "HAGFISH", "LAMPREY", "CHIMERA", "RAY",
        "SKATE", "SAWFISH", "GUITARFISH", "EEL", "MORAY", "CONGER", "HERRING", "SARDINE", "ANCHOVY", "SPRAT",
        "PILCHARD", "SHAD", "ALEWIFE", "MENHADEN", "TUNA", "MACKEREL", "BONITO", "ALBACORE", "SKIPJACK", "BILLFISH",
        "MARLIN", "SAILFISH", "SPEARFISH", "SWORDFISH", "COD", "HADDOCK", "POLLOCK", "WHITING", "HAKE", "LING",
        "BURBOT", "GRENADIER", "FLOUNDER", "SOLE", "PLAICE", "HALIBUT", "TURBOT", "DAB", "BRILL", "MEGRIM",
        "SALMON", "TROUT", "CHAR", "GRAYLING", "WHITEFISH", "SMELT", "CAPELIN", "PIKE", "MUSKELLUNGE", "DACE"
    ],
    nature: [
        "FOREST", "RIVER", "MOUNTAIN", "VALLEY", "CANYON", "DESERT", "MEADOW", "JUNGLE", "STREAM", "PRAIRIE",
        "VOLCANO", "CLIFF", "LAKE", "POND", "GRASS", "MOSS", "FERN", "BRANCH", "STONE", "BOULDER",
        "GLACIER", "ICEBERG", "FJORD", "LAGOON", "ESTUARY", "DELTA", "MARSH", "SWAMP", "BOG", "FEN",
        "MOOR", "HEATH", "TUNDRA", "TAIGA", "SAVANNA", "STEPPE", "BUSHLAND", "SCRUBLAND", "WOODLAND", "GROVE",
        "THICKET", "COPPICE", "ORCHARD", "VINEYARD", "GARDEN", "PARK", "FIELD", "PASTURE", "RANGE", "PLAIN",
        "PLATEAU", "MESA", "BUTTE", "RIDGE", "PEAK", "SUMMIT", "CREST", "SLOPE", "HILLSIDE", "BANK",
        "SHORE", "BEACH", "COAST", "CLIFF", "CAPE", "HEADLAND", "PENINSULA", "ISTHMUS", "ISLAND", "ARCHIPELAGO",
        "ATOLL", "CAY", "REEF", "SHOAL", "SANDBAR", "DUNE", "CAVE", "CAVERN", "GROTTO", "HOLE",
        "PIT", "CRATER", "BASIN", "DEPRESSION", "VALLEY", "GORGE", "RAVINE", "GULLY", "WASH", "BED"
    ],
    sports: [
        "SOCCER", "TENNIS", "HOCKEY", "CRICKET", "RUGBY", "GOLF", "BOXING", "JUDO", "KARATE", "KUNG FU",
        "SKIING", "SURFING", "DIVING", "ROWING", "YOGA", "RACING", "CYCLING", "SKATING", "HIKING", "CLIMBING",
        "FENCING", "ARCHERY", "SHOOTING", "HUNTING", "FISHING", "BOWLING", "CURLING", "SNOOKER", "POOL", "DARTS",
        "CHESS", "POKER", "BRIDGE", "BINGO", "LOTTERY", "ROULETTE", "BLACKJACK", "BACCARAT", "KENO", "CRAPS",
        "BASEBALL", "SOFTBALL", "VOLLEYBALL", "HANDBALL", "NETBALL", "KORFBALL", "ULTIMATE", "QUILTBALL", "DODGEBALL", "KICKBALL",
        "FOOTBALL", "GRIDIRON", "TOUCH", "TAG", "FLAG", "SEVENS", "LEAGUE", "UNION", "AUSSIE", "GAELIC",
        "HURLING", "CAMOGIE", "SHINTY", "LACROSSE", "HOCKEY", "BANDY", "FLOORBALL", "RINK", "ICE", "FIELD",
        "STREET", "BEACH", "INDOOR", "OUTDOOR", "EXTREME", "ADVENTURE", "WATER", "WINTER", "SUMMER", "TEAM",
        "INDIVIDUAL", "DUAL", "COMBAT", "CONTACT", "NONCONTACT", "RACKET", "BAT", "BALL", "STICK", "CLUB"
    ]
}
