export const WORD_BANK: Record<string, string[]> = {
    animals: [
        "TIGER", "ZEBRA", "PANDA", "EAGLE", "SNAKE", "HORSE", "WHALE", "SHARK", "BEAR", "LION",
        "FOX", "WOLF", "RABBIT", "MONKEY", "GIRAFFE", "LEOPARD", "DOLPHIN", "PENGUIN", "OSTRICH", "CAMEL",
        "CHEETAH", "ELEPHANT", "HAMSTER", "KANGAROO", "SQUIRREL", "GORILLA", "PEACOCK", "PANTHER", "BUFFALO", "MEERKAT",
        "ANTELOPE", "PLATYPUS", "STARFISH", "SEAHORSE", "JELLYFISH", "LOBSTER", "SCORPION", "VULTURE", "PELICAN", "FLAMINGO",
        "HEDGEHOG", "RACCOON", "PARROT", "TURTLE", "LIZARD", "CROCODILE", "ALLIGATOR", "RHINOCEROS", "HIPPOPOTAMUS", "CHIMPANZEE",
        "HYENA", "JACKAL", "LEMUR", "ORANGUTAN", "WALRUS", "SEALION", "MANATEE", "NARWHAL", "STINGRAY", "BARRACUDA",
        "PIRANHA", "GOLDFISH", "CATFISH", "SALMON", "TROUT", "SNAPPER", "GROUPER", "MARLIN", "SWORDFISH", "KOALA",
        "PORPOISE", "OCTOPUS", "SQUID", "CUTTLEFISH", "NAUTILUS", "OYSTER", "MUSSEL", "SCALLOP", "ABALONE", "CLAM",
        "SNAIL", "SLUG", "SPIDER", "BEETLE", "BUTTERFLY", "MOTH", "DRAGONFLY", "MANTIS", "CRICKET", "LOCUST",
        "HORNET", "WASP", "TERMITE", "COCKROACH", "LADYBUG", "FIREFLY", "CENTIPEDE", "MILLIPEDE", "WORM", "LEECH"
    ],
    space: [
        "PLANET", "COMET", "STARS", "LUNAR", "ORBIT", "SOLAR", "VENUS", "MARS", "SATURN", "JUPITER",
        "METEOR", "GALAXY", "NEBULA", "ROCKET", "COSMOS", "PULSAR", "QUASAR", "APOLLO", "ASTEROID", "ECLIPSE",
        "MERCURY", "URANUS", "NEPTUNE", "PLUTO", "SUNSPOT", "AURORA", "ZENITH", "AZIMUTH", "HORIZON", "EQUINOX",
        "SOLSTICE", "ZODIAC", "CONSTELLATION", "CASSIOPEIA", "ANDROMEDA", "ORION", "PEGASUS", "SCORPIUS", "SAGITTARIUS", "AQUARIUS",
        "GEMINI", "TAURUS", "LIBRA", "VIRGO", "LEO", "CANCER", "ARIES", "PISCES", "CAPRICORN", "TELESCOPE",
        "SATELLITE", "SPACESHIP", "SHUTTLE", "LANDER", "ROVER", "PROBE", "CAPSULE", "STATION", "MODULE", "SUPERNOVA",
        "THRUSTER", "BOOSTER", "PAYLOAD", "COCKPIT", "AIRLOCK", "GRAVITY", "VACUUM", "PLASMA", "RADIATION", "ASTROPHYSICS",
        "INTERSTELLAR", "MAGNETOSPHERE", "ORBITAL", "TRAJECTORY", "VELOCITY", "LIGHTYEAR", "PARSEC", "UNIVERSE", "MULTIVERSE", "DIMENSION",
        "WORMHOLE", "BLACKHOLE", "EXOPLANET", "HYPERNOVA", "NIGHTSKY", "STARLIGHT", "MOONBEAM", "SUNLIGHT", "TWILIGHT", "MIDNIGHT",
        "INFINITY", "ETERNITY", "VOID", "ABYSS", "DARKNESS", "SPACEWALK", "LAUNCHPAD", "COUNTDOWN", "BLASTOFF", "REENTRY"
    ],
    fruits: [
        "APPLE", "MANGO", "GRAPE", "LEMON", "PEACH", "MELON", "BERRY", "ORANGE", "BANANA", "CHERRY",
        "PAPAYA", "COCONUT", "PINEAPPLE", "KIWI", "PLUM", "PEAR", "LIME", "GUAVA", "APRICOT", "LYCHEE",
        "AVOCADO", "FIG", "DATE", "RAISIN", "PRUNE", "OLIVE", "TOMATO", "EGGPLANT", "PUMPKIN", "SQUASH",
        "CUCUMBER", "PEPPER", "CHILI", "CORN", "STARFRUIT", "DURIAN", "RAMBUTAN", "MANGOSTEEN", "PERSIMMON", "POMEGRANATE",
        "JACKFRUIT", "PASSIONFRUIT", "DRAGONFRUIT", "CRANBERRY", "BLUEBERRY", "RASPBERRY", "BLACKBERRY", "STRAWBERRY", "MULBERRY", "ELDERBERRY",
        "GOOSEBERRY", "CURRANT", "CLEMENTINE", "TANGERINE", "MANDARIN", "POMELO", "KUMQUAT", "NECTARINE", "QUINCE", "LOQUAT",
        "TAMARIND", "SOURSOP", "SALAK", "LONGAN", "JUJUBE", "CANTALOUPE", "HONEYDEW", "WATERMELON", "BREADFRUIT", "PLANTAIN",
        "ACKEE", "NONI", "ACAI", "GOJI", "JABUTICABA", "SAPODILLA", "UGLIFRUIT", "YUZU", "BERGAMOT", "CITRON",
        "GRAPEFRUIT", "LIMEQUAT", "BOYSENBERRY", "LOGANBERRY", "CLOUDBERRY", "HUCKLEBERRY", "CHOKEBERRY", "BILBERRY", "ROWAN", "HAWTHORN",
        "JOGGERS", "MIRACLEFRUIT", "MONKFRUIT", "MARULA", "AMBRA", "BAEL", "CARAMBOLA", "FEIJOA", "LANZONES", "LULO"
    ],
    ocean: [
        "CORAL", "WAVES", "PEARL", "SHORE", "TIDE", "REEF", "KELP", "WHALE", "SHARK", "DOLPHIN",
        "OCTOPUS", "JELLYFISH", "STARFISH", "SEAHORSE", "CLAM", "SEAL", "CRAB", "LOBSTER", "URCHIN", "ALGAE",
        "PLANKTON", "KRILL", "SHRIMP", "PRAWN", "CRAYFISH", "BARNACLE", "LIMPET", "WHELK", "CONCH", "NAUTILUS",
        "ANEMONE", "SPONGE", "HYDROZOAN", "BRYOZOAN", "TUNICATE", "LANCELET", "HAGFISH", "LAMPREY", "CHIMERA", "RAY",
        "SKATE", "SAWFISH", "GUITARFISH", "EEL", "MORAY", "CONGER", "HERRING", "SARDINE", "ANCHOVY", "SPRAT",
        "PILCHARD", "SHAD", "ALEWIFE", "MENHADEN", "TUNA", "MACKEREL", "BONITO", "ALBACORE", "SKIPJACK", "BILLFISH",
        "MARLIN", "SAILFISH", "SPEARFISH", "SWORDFISH", "COD", "HADDOCK", "POLLOCK", "WHITING", "HAKE", "LING",
        "BURBOT", "GRENADIER", "FLOUNDER", "SOLE", "PLAICE", "HALIBUT", "TURBOT", "DAB", "BRILL", "MEGRIM",
        "SALMON", "MAHI MAHI", "WAHOO", "BARRACUDA", "GROUPER", "SNAPPER", "AMBERJACK", "COBIA", "TREVALLY", "NEEDLEFISH"
    ],
    nature: [
        "FOREST", "RIVER", "MOUNTAIN", "VALLEY", "CANYON", "DESERT", "MEADOW", "JUNGLE", "STREAM", "PRAIRIE",
        "VOLCANO", "CLIFF", "LAKE", "POND", "GRASS", "MOSS", "FERN", "BRANCH", "STONE", "BOULDER",
        "GLACIER", "ICEBERG", "FJORD", "LAGOON", "ESTUARY", "DELTA", "MARSH", "SWAMP", "BOG", "FEN",
        "MOOR", "HEATH", "TUNDRA", "TAIGA", "SAVANNA", "STEPPE", "BUSHLAND", "SCRUBLAND", "WOODLAND", "GROVE",
        "THICKET", "COPPICE", "ORCHARD", "VINEYARD", "GARDEN", "PARK", "FIELD", "PASTURE", "RANGE", "PLAIN",
        "PLATEAU", "MESA", "BUTTE", "RIDGE", "PEAK", "SUMMIT", "CREST", "SLOPE", "HILLSIDE", "BANK",
        "SHORE", "BEACH", "COAST", "CLIFF", "CAPE", "HEADLAND", "PENINSULA", "ISTHMUS", "ISLAND", "ARCHIPELAGO",
        "ATOLL", "CAY", "REEF", "SHOAL", "SANDBAR", "DUNE", "CAVE", "CAVERN", "GROTTO", "OASIS",
        "GEYSER", "CRATER", "BASIN", "DEPRESSION", "VALLEY", "GORGE", "RAVINE", "GULLY", "WASH", "WATERFALL"
    ],
    sports: [
        "SOCCER", "TENNIS", "HOCKEY", "CRICKET", "RUGBY", "GOLF", "BOXING", "JUDO", "KARATE", "KUNG FU",
        "SKIING", "SURFING", "DIVING", "ROWING", "YOGA", "RACING", "CYCLING", "SKATING", "HIKING", "CLIMBING",
        "FENCING", "ARCHERY", "SHOOTING", "HUNTING", "FISHING", "BOWLING", "CURLING", "SNOOKER", "POOL", "DARTS",
        "CHESS", "POKER", "BRIDGE", "BILLIARDS", "BADMINTON", "SQUASH", "RACQUETBALL", "HANDBALL", "WATERPOLO", "WRESTLING",
        "BASEBALL", "SOFTBALL", "VOLLEYBALL", "HANDBALL", "NETBALL", "KORFBALL", "ULTIMATE", "QUILTBALL", "DODGEBALL", "KICKBALL",
        "FOOTBALL", "GRIDIRON", "TOUCH", "TAG", "FLAG", "SEVENS", "LEAGUE", "UNION", "ATHLETICS", "GYMNASTICS",
        "HURLING", "CAMOGIE", "SHINTY", "LACROSSE", "HOCKEY", "BANDY", "FLOORBALL", "TRIATHLON", "MARATHON", "SPRINT",
        "MOTOCROSS", "NASCAR", "FORMULA", "RALLY", "DRIFTING", "KARTING", "BMX", "SKATEBOARD", "SNOWBOARD", "BOBSLEIGH",
        "LUGE", "SKELETON", "BIATHLON", "CURLING", "TAEKWONDO", "JIUJITSU", "MMA", "MUAYTHAI", "SAMBO", "SUMO"
    ]
}